name: Build-Docker-Image

on: 
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
    - master
    - dev
jobs:
  build_docker_img:
     runs-on: ubuntu-latest
     env:
       TAG: netty
       VERSION: v1
     
     steps:
     - name: Get code
       uses: actions/checkout@v3
     - name: build Jarfile
       run: mvn install
     - name: upload artifcats
       uses: actions/upload-artifact@v3.1.1
       with:
        name: project.war
        path: src
     
     
     - name: Build Docker Image
       run: docker build -t $TAG .
       
       
     - name: Image Scan
       uses: aquasecurity/trivy-action@master
       with:
          image-ref: '${{ env.TAG }}:${{ env.VERSION }}'
          security-checks: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'
          
     - name: Upload the scan result to GitHub Security
       uses: github/codeql-action/upload-sarif@v2
       with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'image'







